services:
  - type: web
    name: pdf-to-word
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn --timeout 120 app:app"  # Timeout increase for heavy processing
    envVars:
      - key: FLASK_ENV
        value: production
